/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boletinextra;

/**
 *
 * @author dam1
 */
public class Bonoloto extends javax.swing.JFrame {

    /**
     * Creates new form Bonoloto
     */
    public Bonoloto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButtonTrenta = new javax.swing.JButton();
        jButtonCuarenta = new javax.swing.JButton();
        jButtonVeinte = new javax.swing.JButton();
        jLUno = new javax.swing.JLabel();
        jButtondiez = new javax.swing.JButton();
        jButtonUno = new javax.swing.JButton();
        jButtonOnce = new javax.swing.JButton();
        jButtonVeintiUno = new javax.swing.JButton();
        jButtonTrentayUno = new javax.swing.JButton();
        jButtonCuarentaYUno = new javax.swing.JButton();
        jButtonDos = new javax.swing.JButton();
        jButtonDoce = new javax.swing.JButton();
        jButtonVeintiDos = new javax.swing.JButton();
        jButtonTrentaYDos = new javax.swing.JButton();
        jButtoncuarentaYDos = new javax.swing.JButton();
        jButtonTres = new javax.swing.JButton();
        jButtonTrece = new javax.swing.JButton();
        jButtonVeintiTres = new javax.swing.JButton();
        jButtonTreintaYTres = new javax.swing.JButton();
        jButtonCuarentaYtres = new javax.swing.JButton();
        jButtonCuatro = new javax.swing.JButton();
        jButtonCatorce = new javax.swing.JButton();
        jButtonVeintiCuatro = new javax.swing.JButton();
        jButtonTreintaYCuatro = new javax.swing.JButton();
        jButtonCuarentaYCuatro = new javax.swing.JButton();
        jButtonCinco = new javax.swing.JButton();
        jButtonQuince = new javax.swing.JButton();
        jButtonVeinticinco = new javax.swing.JButton();
        jButtonTrentayCinco = new javax.swing.JButton();
        jButtonCuarentaYCinco = new javax.swing.JButton();
        jButtonSeis = new javax.swing.JButton();
        jButtonDiecieis = new javax.swing.JButton();
        jButtonVeintiSeis = new javax.swing.JButton();
        jButtonTrentaYSeis = new javax.swing.JButton();
        jButtonSiete = new javax.swing.JButton();
        jButtonCuarentaYSeis = new javax.swing.JButton();
        jButtonDiesisite = new javax.swing.JButton();
        jButtonVeintiSiete = new javax.swing.JButton();
        jButtonTrentaYSiete = new javax.swing.JButton();
        jButtonCuarentaYSiete = new javax.swing.JButton();
        jButtonOcho = new javax.swing.JButton();
        jButtonDieciOcho = new javax.swing.JButton();
        jButtonVeintiOcho = new javax.swing.JButton();
        jButtonCinco14 = new javax.swing.JButton();
        jButtonCinco15 = new javax.swing.JButton();
        jButtonNueve = new javax.swing.JButton();
        jButtonDieciNueve = new javax.swing.JButton();
        jButtonVeintiNueve = new javax.swing.JButton();
        jButtonTreintaYNueve = new javax.swing.JButton();
        jButtonCuarentaYNuevo = new javax.swing.JButton();

        jButton13.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 204)));

        jButtonTrenta.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTrenta.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTrenta.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTrenta.setText("30");
        jButtonTrenta.setMultiClickThreshhold(30L);

        jButtonCuarenta.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarenta.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarenta.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarenta.setText("40");
        jButtonCuarenta.setName("40"); // NOI18N

        jButtonVeinte.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeinte.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeinte.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeinte.setText("20");
        jButtonVeinte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonVeinte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeinte.setMaximumSize(new java.awt.Dimension(72, 23));
        jButtonVeinte.setMinimumSize(new java.awt.Dimension(72, 23));
        jButtonVeinte.setName("20"); // NOI18N
        jButtonVeinte.setPreferredSize(new java.awt.Dimension(72, 23));
        jButtonVeinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeinteActionPerformed(evt);
            }
        });

        jLUno.setBackground(new java.awt.Color(255, 255, 255));
        jLUno.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLUno.setForeground(new java.awt.Color(0, 0, 0));
        jLUno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLUno.setText("1");
        jLUno.setAlignmentX(0.5F);
        jLUno.setAutoscrolls(true);
        jLUno.setMaximumSize(new java.awt.Dimension(72, 23));
        jLUno.setMinimumSize(new java.awt.Dimension(8, 18));
        jLUno.setPreferredSize(new java.awt.Dimension(8, 18));

        jButtondiez.setBackground(new java.awt.Color(255, 255, 255));
        jButtondiez.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtondiez.setForeground(new java.awt.Color(0, 0, 0));
        jButtondiez.setText("10");
        jButtondiez.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtondiez.setName("10"); // NOI18N
        jButtondiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondiezActionPerformed(evt);
            }
        });

        jButtonUno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonUno.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonUno.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUno.setText("1");
        jButtonUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUno.setName("10"); // NOI18N
        jButtonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnoActionPerformed(evt);
            }
        });

        jButtonOnce.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOnce.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonOnce.setForeground(new java.awt.Color(0, 0, 0));
        jButtonOnce.setText("11");
        jButtonOnce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOnce.setName("10"); // NOI18N
        jButtonOnce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnceActionPerformed(evt);
            }
        });

        jButtonVeintiUno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiUno.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiUno.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiUno.setText("21");
        jButtonVeintiUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiUno.setName("10"); // NOI18N
        jButtonVeintiUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiUnoActionPerformed(evt);
            }
        });

        jButtonTrentayUno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTrentayUno.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTrentayUno.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTrentayUno.setText("31");
        jButtonTrentayUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTrentayUno.setName("10"); // NOI18N
        jButtonTrentayUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrentayUnoActionPerformed(evt);
            }
        });

        jButtonCuarentaYUno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarentaYUno.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarentaYUno.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarentaYUno.setText("41");
        jButtonCuarentaYUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuarentaYUno.setName("10"); // NOI18N
        jButtonCuarentaYUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuarentaYUnoActionPerformed(evt);
            }
        });

        jButtonDos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDos.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonDos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDos.setText("2");
        jButtonDos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDos.setName("10"); // NOI18N
        jButtonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDosActionPerformed(evt);
            }
        });

        jButtonDoce.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDoce.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonDoce.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDoce.setText("12");
        jButtonDoce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDoce.setName("10"); // NOI18N
        jButtonDoce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoceActionPerformed(evt);
            }
        });

        jButtonVeintiDos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiDos.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiDos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiDos.setText("22");
        jButtonVeintiDos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiDos.setName("10"); // NOI18N
        jButtonVeintiDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiDosActionPerformed(evt);
            }
        });

        jButtonTrentaYDos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTrentaYDos.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTrentaYDos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTrentaYDos.setText("32");
        jButtonTrentaYDos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTrentaYDos.setName("10"); // NOI18N
        jButtonTrentaYDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrentaYDosActionPerformed(evt);
            }
        });

        jButtoncuarentaYDos.setBackground(new java.awt.Color(255, 255, 255));
        jButtoncuarentaYDos.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtoncuarentaYDos.setForeground(new java.awt.Color(0, 0, 0));
        jButtoncuarentaYDos.setText("42");
        jButtoncuarentaYDos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtoncuarentaYDos.setName("10"); // NOI18N
        jButtoncuarentaYDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncuarentaYDosActionPerformed(evt);
            }
        });

        jButtonTres.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTres.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTres.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTres.setText("3");
        jButtonTres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTres.setName("10"); // NOI18N
        jButtonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTresActionPerformed(evt);
            }
        });

        jButtonTrece.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTrece.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTrece.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTrece.setText("13");
        jButtonTrece.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTrece.setName("10"); // NOI18N
        jButtonTrece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreceActionPerformed(evt);
            }
        });

        jButtonVeintiTres.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiTres.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiTres.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiTres.setText("23");
        jButtonVeintiTres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiTres.setName("10"); // NOI18N
        jButtonVeintiTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiTresActionPerformed(evt);
            }
        });

        jButtonTreintaYTres.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTreintaYTres.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTreintaYTres.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTreintaYTres.setText("33");
        jButtonTreintaYTres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTreintaYTres.setName("10"); // NOI18N
        jButtonTreintaYTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreintaYTresActionPerformed(evt);
            }
        });

        jButtonCuarentaYtres.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarentaYtres.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarentaYtres.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarentaYtres.setText("43");
        jButtonCuarentaYtres.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuarentaYtres.setName("10"); // NOI18N
        jButtonCuarentaYtres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuarentaYtresActionPerformed(evt);
            }
        });

        jButtonCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuatro.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuatro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuatro.setText("4");
        jButtonCuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuatro.setName("10"); // NOI18N
        jButtonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuatroActionPerformed(evt);
            }
        });

        jButtonCatorce.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCatorce.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCatorce.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCatorce.setText("14");
        jButtonCatorce.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCatorce.setName("10"); // NOI18N
        jButtonCatorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCatorceActionPerformed(evt);
            }
        });

        jButtonVeintiCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiCuatro.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiCuatro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiCuatro.setText("24");
        jButtonVeintiCuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiCuatro.setName("10"); // NOI18N
        jButtonVeintiCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiCuatroActionPerformed(evt);
            }
        });

        jButtonTreintaYCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTreintaYCuatro.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTreintaYCuatro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTreintaYCuatro.setText("34");
        jButtonTreintaYCuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTreintaYCuatro.setName("10"); // NOI18N
        jButtonTreintaYCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreintaYCuatroActionPerformed(evt);
            }
        });

        jButtonCuarentaYCuatro.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarentaYCuatro.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarentaYCuatro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarentaYCuatro.setText("44");
        jButtonCuarentaYCuatro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuarentaYCuatro.setName("10"); // NOI18N
        jButtonCuarentaYCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuarentaYCuatroActionPerformed(evt);
            }
        });

        jButtonCinco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCinco.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCinco.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCinco.setText("5");
        jButtonCinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCinco.setName("10"); // NOI18N
        jButtonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCincoActionPerformed(evt);
            }
        });

        jButtonQuince.setBackground(new java.awt.Color(255, 255, 255));
        jButtonQuince.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonQuince.setForeground(new java.awt.Color(0, 0, 0));
        jButtonQuince.setText("15");
        jButtonQuince.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonQuince.setName("10"); // NOI18N
        jButtonQuince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuinceActionPerformed(evt);
            }
        });

        jButtonVeinticinco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeinticinco.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeinticinco.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeinticinco.setText("25");
        jButtonVeinticinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeinticinco.setName("10"); // NOI18N
        jButtonVeinticinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeinticincoActionPerformed(evt);
            }
        });

        jButtonTrentayCinco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTrentayCinco.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTrentayCinco.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTrentayCinco.setText("35");
        jButtonTrentayCinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTrentayCinco.setName("10"); // NOI18N
        jButtonTrentayCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrentayCincoActionPerformed(evt);
            }
        });

        jButtonCuarentaYCinco.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarentaYCinco.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarentaYCinco.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarentaYCinco.setText("45");
        jButtonCuarentaYCinco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuarentaYCinco.setName("10"); // NOI18N
        jButtonCuarentaYCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuarentaYCincoActionPerformed(evt);
            }
        });

        jButtonSeis.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSeis.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonSeis.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSeis.setText("6");
        jButtonSeis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSeis.setName("10"); // NOI18N
        jButtonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeisActionPerformed(evt);
            }
        });

        jButtonDiecieis.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDiecieis.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonDiecieis.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDiecieis.setText("16");
        jButtonDiecieis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDiecieis.setName("10"); // NOI18N
        jButtonDiecieis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiecieisActionPerformed(evt);
            }
        });

        jButtonVeintiSeis.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiSeis.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiSeis.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiSeis.setText("26");
        jButtonVeintiSeis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiSeis.setName("10"); // NOI18N
        jButtonVeintiSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiSeisActionPerformed(evt);
            }
        });

        jButtonTrentaYSeis.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTrentaYSeis.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTrentaYSeis.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTrentaYSeis.setText("36");
        jButtonTrentaYSeis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTrentaYSeis.setName("10"); // NOI18N
        jButtonTrentaYSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrentaYSeisActionPerformed(evt);
            }
        });

        jButtonSiete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSiete.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonSiete.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSiete.setText("7");
        jButtonSiete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSiete.setName("10"); // NOI18N
        jButtonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSieteActionPerformed(evt);
            }
        });

        jButtonCuarentaYSeis.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarentaYSeis.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarentaYSeis.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarentaYSeis.setText("46");
        jButtonCuarentaYSeis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuarentaYSeis.setName("10"); // NOI18N
        jButtonCuarentaYSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuarentaYSeisActionPerformed(evt);
            }
        });

        jButtonDiesisite.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDiesisite.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonDiesisite.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDiesisite.setText("17");
        jButtonDiesisite.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDiesisite.setName("10"); // NOI18N
        jButtonDiesisite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDiesisiteActionPerformed(evt);
            }
        });

        jButtonVeintiSiete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiSiete.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiSiete.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiSiete.setText("27");
        jButtonVeintiSiete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiSiete.setName("10"); // NOI18N
        jButtonVeintiSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiSieteActionPerformed(evt);
            }
        });

        jButtonTrentaYSiete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTrentaYSiete.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTrentaYSiete.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTrentaYSiete.setText("37");
        jButtonTrentaYSiete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTrentaYSiete.setName("10"); // NOI18N
        jButtonTrentaYSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrentaYSieteActionPerformed(evt);
            }
        });

        jButtonCuarentaYSiete.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarentaYSiete.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarentaYSiete.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarentaYSiete.setText("47");
        jButtonCuarentaYSiete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuarentaYSiete.setName("10"); // NOI18N
        jButtonCuarentaYSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuarentaYSieteActionPerformed(evt);
            }
        });

        jButtonOcho.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOcho.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonOcho.setForeground(new java.awt.Color(0, 0, 0));
        jButtonOcho.setText("8");
        jButtonOcho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOcho.setName("10"); // NOI18N
        jButtonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOchoActionPerformed(evt);
            }
        });

        jButtonDieciOcho.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDieciOcho.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonDieciOcho.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDieciOcho.setText("18");
        jButtonDieciOcho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDieciOcho.setName("10"); // NOI18N
        jButtonDieciOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDieciOchoActionPerformed(evt);
            }
        });

        jButtonVeintiOcho.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiOcho.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiOcho.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiOcho.setText("28");
        jButtonVeintiOcho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiOcho.setName("10"); // NOI18N
        jButtonVeintiOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiOchoActionPerformed(evt);
            }
        });

        jButtonCinco14.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCinco14.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCinco14.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCinco14.setText("38");
        jButtonCinco14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCinco14.setName("10"); // NOI18N
        jButtonCinco14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCinco14ActionPerformed(evt);
            }
        });

        jButtonCinco15.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCinco15.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCinco15.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCinco15.setText("48");
        jButtonCinco15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCinco15.setName("10"); // NOI18N
        jButtonCinco15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCinco15ActionPerformed(evt);
            }
        });

        jButtonNueve.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNueve.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonNueve.setForeground(new java.awt.Color(0, 0, 0));
        jButtonNueve.setText("9");
        jButtonNueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNueve.setName("10"); // NOI18N
        jButtonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNueveActionPerformed(evt);
            }
        });

        jButtonDieciNueve.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDieciNueve.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonDieciNueve.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDieciNueve.setText("19");
        jButtonDieciNueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonDieciNueve.setName("10"); // NOI18N
        jButtonDieciNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDieciNueveActionPerformed(evt);
            }
        });

        jButtonVeintiNueve.setBackground(new java.awt.Color(255, 255, 255));
        jButtonVeintiNueve.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonVeintiNueve.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVeintiNueve.setText("29");
        jButtonVeintiNueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVeintiNueve.setName("10"); // NOI18N
        jButtonVeintiNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVeintiNueveActionPerformed(evt);
            }
        });

        jButtonTreintaYNueve.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTreintaYNueve.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonTreintaYNueve.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTreintaYNueve.setText("39");
        jButtonTreintaYNueve.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTreintaYNueve.setName("10"); // NOI18N
        jButtonTreintaYNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTreintaYNueveActionPerformed(evt);
            }
        });

        jButtonCuarentaYNuevo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCuarentaYNuevo.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButtonCuarentaYNuevo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCuarentaYNuevo.setText("49");
        jButtonCuarentaYNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCuarentaYNuevo.setName("10"); // NOI18N
        jButtonCuarentaYNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCuarentaYNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLUno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDiesisite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeintiSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTrentaYSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCuarentaYSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDiecieis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeintiSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTrentaYSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCuarentaYSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonQuince, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeinticinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTrentayCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCuarentaYCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonCatorce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeintiCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTreintaYCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCuarentaYCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonTrece, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeintiTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTreintaYTres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCuarentaYtres, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtondiez, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonOnce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonVeintiUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonTrentayUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCuarentaYUno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonVeinte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonTrenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCuarenta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeintiDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTrentaYDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtoncuarentaYDos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDieciOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeintiOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCinco14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCinco15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonDieciNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonVeintiNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTreintaYNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCuarentaYNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLUno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtondiez, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonTrenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCuarenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVeinte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonVeintiUno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonTrentayUno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCuarentaYUno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonUno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonOnce, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDoce, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeintiDos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrentaYDos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtoncuarentaYDos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrece, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeintiTres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTreintaYTres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuarentaYtres, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCatorce, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeintiCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTreintaYCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuarentaYCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonQuince, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeinticinco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrentayCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuarentaYCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiecieis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeintiSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrentaYSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuarentaYSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiesisite, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeintiSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTrentaYSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuarentaYSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDieciOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeintiOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCinco14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCinco15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDieciNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVeintiNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTreintaYNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCuarentaYNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtondiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondiezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtondiezActionPerformed

    private void jButtonVeinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeinteActionPerformed

    private void jButtonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUnoActionPerformed

    private void jButtonOnceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOnceActionPerformed

    private void jButtonVeintiUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiUnoActionPerformed

    private void jButtonTrentayUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrentayUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrentayUnoActionPerformed

    private void jButtonCuarentaYUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuarentaYUnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuarentaYUnoActionPerformed

    private void jButtonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDosActionPerformed

    private void jButtonDoceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDoceActionPerformed

    private void jButtonVeintiDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiDosActionPerformed

    private void jButtonTrentaYDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrentaYDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrentaYDosActionPerformed

    private void jButtoncuarentaYDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncuarentaYDosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncuarentaYDosActionPerformed

    private void jButtonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTresActionPerformed

    private void jButtonTreceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTreceActionPerformed

    private void jButtonVeintiTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiTresActionPerformed

    private void jButtonTreintaYTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreintaYTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTreintaYTresActionPerformed

    private void jButtonCuarentaYtresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuarentaYtresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuarentaYtresActionPerformed

    private void jButtonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuatroActionPerformed

    private void jButtonCatorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCatorceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCatorceActionPerformed

    private void jButtonVeintiCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiCuatroActionPerformed

    private void jButtonTreintaYCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreintaYCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTreintaYCuatroActionPerformed

    private void jButtonCuarentaYCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuarentaYCuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuarentaYCuatroActionPerformed

    private void jButtonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCincoActionPerformed

    private void jButtonQuinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonQuinceActionPerformed

    private void jButtonVeinticincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeinticincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeinticincoActionPerformed

    private void jButtonTrentayCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrentayCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrentayCincoActionPerformed

    private void jButtonCuarentaYCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuarentaYCincoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuarentaYCincoActionPerformed

    private void jButtonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeisActionPerformed

    private void jButtonDiecieisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiecieisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDiecieisActionPerformed

    private void jButtonVeintiSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiSeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiSeisActionPerformed

    private void jButtonTrentaYSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrentaYSeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrentaYSeisActionPerformed

    private void jButtonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSieteActionPerformed

    private void jButtonCuarentaYSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuarentaYSeisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuarentaYSeisActionPerformed

    private void jButtonDiesisiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDiesisiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDiesisiteActionPerformed

    private void jButtonVeintiSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiSieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiSieteActionPerformed

    private void jButtonTrentaYSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrentaYSieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTrentaYSieteActionPerformed

    private void jButtonCuarentaYSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuarentaYSieteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuarentaYSieteActionPerformed

    private void jButtonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonOchoActionPerformed

    private void jButtonDieciOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDieciOchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDieciOchoActionPerformed

    private void jButtonVeintiOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiOchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiOchoActionPerformed

    private void jButtonCinco14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCinco14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCinco14ActionPerformed

    private void jButtonCinco15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCinco15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCinco15ActionPerformed

    private void jButtonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNueveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNueveActionPerformed

    private void jButtonDieciNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDieciNueveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDieciNueveActionPerformed

    private void jButtonVeintiNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVeintiNueveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVeintiNueveActionPerformed

    private void jButtonTreintaYNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTreintaYNueveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTreintaYNueveActionPerformed

    private void jButtonCuarentaYNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCuarentaYNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCuarentaYNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bonoloto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bonoloto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButtonCatorce;
    private javax.swing.JButton jButtonCinco;
    private javax.swing.JButton jButtonCinco14;
    private javax.swing.JButton jButtonCinco15;
    private javax.swing.JButton jButtonCuarenta;
    private javax.swing.JButton jButtonCuarentaYCinco;
    private javax.swing.JButton jButtonCuarentaYCuatro;
    private javax.swing.JButton jButtonCuarentaYNuevo;
    private javax.swing.JButton jButtonCuarentaYSeis;
    private javax.swing.JButton jButtonCuarentaYSiete;
    private javax.swing.JButton jButtonCuarentaYUno;
    private javax.swing.JButton jButtonCuarentaYtres;
    private javax.swing.JButton jButtonCuatro;
    private javax.swing.JButton jButtonDieciNueve;
    private javax.swing.JButton jButtonDieciOcho;
    private javax.swing.JButton jButtonDiecieis;
    private javax.swing.JButton jButtonDiesisite;
    private javax.swing.JButton jButtonDoce;
    private javax.swing.JButton jButtonDos;
    private javax.swing.JButton jButtonNueve;
    private javax.swing.JButton jButtonOcho;
    private javax.swing.JButton jButtonOnce;
    private javax.swing.JButton jButtonQuince;
    private javax.swing.JButton jButtonSeis;
    private javax.swing.JButton jButtonSiete;
    private javax.swing.JButton jButtonTrece;
    private javax.swing.JButton jButtonTreintaYCuatro;
    private javax.swing.JButton jButtonTreintaYNueve;
    private javax.swing.JButton jButtonTreintaYTres;
    private javax.swing.JButton jButtonTrenta;
    private javax.swing.JButton jButtonTrentaYDos;
    private javax.swing.JButton jButtonTrentaYSeis;
    private javax.swing.JButton jButtonTrentaYSiete;
    private javax.swing.JButton jButtonTrentayCinco;
    private javax.swing.JButton jButtonTrentayUno;
    private javax.swing.JButton jButtonTres;
    private javax.swing.JButton jButtonUno;
    private javax.swing.JButton jButtonVeinte;
    private javax.swing.JButton jButtonVeintiCuatro;
    private javax.swing.JButton jButtonVeintiDos;
    private javax.swing.JButton jButtonVeintiNueve;
    private javax.swing.JButton jButtonVeintiOcho;
    private javax.swing.JButton jButtonVeintiSeis;
    private javax.swing.JButton jButtonVeintiSiete;
    private javax.swing.JButton jButtonVeintiTres;
    private javax.swing.JButton jButtonVeintiUno;
    private javax.swing.JButton jButtonVeinticinco;
    private javax.swing.JButton jButtoncuarentaYDos;
    private javax.swing.JButton jButtondiez;
    private javax.swing.JLabel jLUno;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
